[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -DLV_CONF_INCLUDE_SIMPLE -I${PROJECT_DIR}
lib_deps =
    lvgl/lvgl@^8.4.0
    teemuatlut/TMCStepper@^0.7.3
    gin66/FastAccelStepper@^1.0.0
    moononournation/GFX Library for Arduino@^1.4.0
    me-no-dev/ESPAsyncWebServer@^1.2.3
    me-no-dev/AsyncTCP@^1.1.1

[env:native]
platform = native
build_flags = -DUNIT_TEST -std=c++17
test_framework = unity
build_src_filter = -<*>
test_filter = test_native/test_*
